
function(staticLibDir name out)
    set(${out} ${ANDROID_TARGET_OUT_DIR}/${ANDROID_OBJ_DIR}/STATIC_LIBRARIES/lib${name}_intermediates/lib${name}.a PARENT_SCOPE)
endfunction()

function(sharedLibDir name out)
    set(${out} ${ANDROID_TARGET_OUT_DIR}/${ANDROID_OBJ_DIR}/SHARED_LIBRARIES/lib${name}_intermediates/lib${name}.so PARENT_SCOPE)
endfunction()

function(android_target_link_static_libraries target ...)
    math(EXPR NUM "${ARGC} - 1")
    foreach(i RANGE 1 ${NUM})
        set(name ${ARGV${i}})
        if("${name}" MATCHES "^lib.*")
            string(REPLACE "lib" "" name "${name}")
        endif()
        target_link_libraries(${target} ${ANDROID_TARGET_OUT_DIR}/${ANDROID_OBJ_DIR}/STATIC_LIBRARIES/lib${name}_intermediates/lib${name}.a)
    endforeach()
endfunction()

function(android_target_link_shared_libraries target ...)
    math(EXPR NUM "${ARGC} - 1")
    foreach(i RANGE 1 ${NUM})
        set(name ${ARGV${i}})
        if("${name}" MATCHES "^lib.*")
            string(REPLACE "lib" "" name "${name}")
        endif()
        target_link_libraries(${target} ${name})
    endforeach()
endfunction()