if(ANDROID_CPU_VARIANT STREQUAL cortex-a15)
  set(ARCH_VARIANT_CLFAGS -mcpu=cortex-a15 -mfpu=neon-vfpv4)
  set(ARCH_VARIANT_LDLFAGS -Wl,--no-fix-cortex-a8)
  set(local_arch_has_lpae ON)
else if(ANDROID_CPU_VARIANT STREQUAL cortex-a9)
  set(ARCH_VARIANT_CLFAGS -mcpu=cortex-a9 -mfpu=neon)
else if(ANDROID_CPU_VARIANT STREQUAL cortex-a8)
  set(ARCH_VARIANT_CLFAGS -mcpu=cortex-a8 -mfpu=neon)
  set(ARCH_VARIANT_LDLFAGS -Wl,--fix-cortex-a8)
else if(ANDROID_CPU_VARIANT MATCHES "(cortex-a7|cortex-a53|cortex-a53.a57)")
  set(ARCH_VARIANT_CLFAGS -mcpu=cortex-a7 -mfpu=neon-vfpv4)
  set(ARCH_VARIANT_LDLFAGS -Wl,--no-fix-cortex-a8)
  set(local_arch_has_lpae ON)
else if(ANDROID_CPU_VARIANT STREQUAL cortex-a5)
  set(ARCH_VARIANT_CLFAGS -mcpu=cortex-a7 -mfpu=neon-vfpv4)
  set(ARCH_VARIANT_LDLFAGS -Wl,--no-fix-cortex-a8)
else()
  set(ARCH_VARIANT_CLFAGS -march=armv7-a -mfpu=neon)
  set(ARCH_VARIANT_LDLFAGS -Wl,--fix-cortex-a8)
endif()

if(local_arch_has_lpae)
  list(APPEND ARCH_VARIANT_CLFAGS -D__ARM_FEATURE_LPAE=1)
endif()
list(APPEND ARCH_VARIANT_CLFAGS -mfloat-abi=softfp)